const Quotation = require('../models/Quotation');
const { successResponse } = require('../models/ResponseModel');

const getQuotations = async (req, res) => {
    const quotations = await Quotation.find({ userId: req.user._id }).populate('products');
    return successResponse(quotations, "Quotations generated by user");
};

module.exports = {
    getQuotations
};
