name: Deploy Node.js MVC App

on:
  push:
    branches:
      - main  # Change this to your main branch or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust according to your app's requirements

      - name: Install dependencies
        run: npm install

      - name: Build the app (optional)
        run: npm run build  # Adjust if you have a build command

      - name: Deploy to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your SSH private key in GitHub secrets
          VM_IP: ${{ secrets.VM_IP }}                      # Store your EC2 public IP in GitHub secrets
          SSH_USER: "ubuntu"                               # Change if using a different user
        run: |
          # Write the private key to a file
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy application files to the EC2 instance
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./ ubuntu@$VM_IP:/home/ubuntu/igm  # Adjust path as necessary

          # SSH into the EC2 instance and run commands to install dependencies and start the app
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$VM_IP << 'EOF'
            cd /home/ubuntu/igm
            npm install
            pm2 restart igm || pm2 start server.js --name "igm" -- run start:prod  # Adjust command as necessary
          EOF
